import pandas as pd


def get_rsi_values(close, time_period=14):
    """
    Relative Strength Index (RSI) is a momentum oscillator that measures the speed and change of price movements.
    RSI oscillates between zero and 100. Traditionally, and according to Wilder,
    RSI is considered overbought when above 70 and oversold when below 30.
    Signals can also be generated by looking for divergences, failure swings and centerline crossovers.
    RSI can also be used to identify the general trend.
    :return: <class 'numpy.ndarray'> (len(close),)
    """
    ## get the price diff
    delta = close.diff()

    ## positive gains (up) and negative gains (down) Series
    up, down = delta.copy(), delta.copy()
    up[up < 0] = 0
    down[down > 0] = 0

    # EMAs of ups and downs
    _gain = up.ewm(span=time_period, min_periods=time_period - 1).mean()
    _loss = down.abs().ewm(span=time_period, min_periods=time_period - 1).mean()

    RS = _gain / _loss
    result = pd.Series(100. - (100. / (1. + RS)), name="RSI")
    # result = result.dropna()
    return result



def get_rsi_int_labels_ts(rsi, overbought_level=70, oversold_level=30):
    # raw_signal = get_rsi_values()
    raw_signal = rsi
    labelled_signal = raw_signal.copy()
    labelled_signal[labelled_signal < oversold_level] = 1
    labelled_signal[labelled_signal > overbought_level] = -1
    labelled_signal[(labelled_signal > oversold_level) & (labelled_signal < overbought_level)] = 0
    rsi_signal = labelled_signal
    return rsi_signal